services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: Dockerfile
    startCommand: >
      composer install --no-interaction --prefer-dist --optimize-autoloader &&
      php artisan migrate --force &&
      php artisan config:cache &&
      php artisan route:cache
  - type: worker
    name: laravel-queue
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    startCommand: > 
      composer install --no-interaction --prefer-dist --optimize-autoloader &&
      php artisan queue:work --sleep=3 --tries=3

  - type: cron
    name: laravel-scheduler
    env: docker
    schedule: "* * * * *"
    dockerContext: .
    dockerfilePath: Dockerfile
    startCommand: > 
      composer install --no-interaction --prefer-dist --optimize-autoloader &&
      php artisan schedule:run