name: Tests

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: laravel
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_pgsql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
      
      - name: Install Node.js dependencies
        run: npm ci

      - name: Build assets with Vite
        run: npm run build

      - name: Copy .env
        run: cp .env.testing .env

      - name: Generate Laravel key
        run: php artisan key:generate

      - name: Run migrations
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: laravel
          DB_USERNAME: user
          DB_PASSWORD: password
        run: |
          php artisan config:clear
          php artisan migrate --force

      - name: Run Laravel Tests
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: laravel
          DB_USERNAME: user
          DB_PASSWORD: password
        run: php artisan test
